### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by EvilLooney** [roquie/laravel-perpage-resolver#3]
Hi,

Thanks for the package. I really think something like this should be part of the Laravel core.

I have a question though, starting in Laravel 5.2+ I think, the User model extends the `Illuminate\Foundation\Auth\User` model (instead of `Illuminate\Database\Eloquent\Model`). I was wondering if I should just copy and paste that class into my project and extend it with yours or do you think you should add the modified class into this project?

Or maybe you are handling this another way in your other projects?

Thanks!

**Comment by roquie** [comment]
Hi,

Currently design does not allow add package functionality if other class extend `Model` class. It's possible use dirty workaround -- copy paste code to needed models. But, I'm not recommend use this method.

I created new branch `per_page_trait `. You can try new method. Your need to update the code using [composer](http://vvv.tobiassjosten.net/php/have-composer-use-development-branches/)  and then use the `PerPageResolverTrait` in the you User model.

After that, she is work for you?

**Comment by roquie** [comment]
@EvilLooney I updated the library (master branch). Check it, please.
